### ISSUE TITLE
Trigger error checking on form load

### ISSUE THREAD

**Issue by gmgarrison** [the94air/formjs#1]
I'm using garlic.js (http://garlicjs.org) to auto-persist unsubmitted form entries to local storage. When the form loads the page if an entry has the "formjs-error" class it registers as empty even if there's a saved entry there. Is there a way I can manually trigger the checking JS on page load to clear the incorrect error conditions?

**Comment by the94air** [comment]
I think you should check the garlic.js repo because `formjs-error` is just a class. No js is involved. What are you using for the validation? Can you show me some code? I hope that I can help you on this.

**Comment by gmgarrison** [comment]
Thanks for the idea. I ended up tying the two together manually. I wrote a function in formjs.js to iterate on each formjs-error field and remove the class if it's not empty. Then I called that function in the onLoad() method that loads any persisted data in garlicjs. Seems to work so I'm happy!
